"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import CatProvider from "@/context/CatContext";
import { ProfileProvider } from "@/context/ProfileContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProfileProvider>
          <CatProvider>
            <AuthProvider>{children}</AuthProvider>
          </CatProvider>
        </ProfileProvider>

        {/* {children} */}
      </body>
    </html>
  );
}
